[package]
name = "snake_game"
version = "0.1.0"
edition = "2018"

[dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3"
web-sys = { version = "0.3", features = ["Window", "Document", "CanvasRenderingContext2d"] }

[lib]
crate-type = ["cdylib", "rlib"]
