version: "3"
services:
 app:
  container_name: node-app
  depends_on:
   - redis-server
   - mysql_database
  build: .
  restart: always
  ports:
   - "3000:3000"
 redis-server:
  container_name: redis-cache
  image: "redis:latest"
  restart: always
  ports:
   - "6379:6379"
 mysql_database:
  container_name: mysqlDB
  build: ./db
  restart: always
  ports:
   - "3306:3306"